---
engines:
 rubocop:
   enabled: true
   exclude_paths:
     - config/engines.yml
 duplication: 
   exclude_paths:
     - config/engines.yml
 metric:
   exclude_paths:
     - config/engines.yml
 coverage:
   exclude_paths:
     - config/engines.yml
exclude_paths:
  - '.bundle/**'
  - 'spec/**/*'
  - '*.min.js'
  - '**/tests/**' 
  - 'system/**'
  - 'system/**/*'
